# This environment installs the latests released version of hydromt-sfincs,
# including some dependencies to run the examples 
name: hydromt-sfincs

channels:
  - conda-forge

dependencies:
  - cartopy>=0.20 # to run examples
  - descartes # to run examples
  - ffmpeg  # to run examples (animation)
  - hydromt==0.6.0
  - hydromt_sfincs
  - jupyterlab # to run examples
  - matplotlib==3.5.* # to run examples / https://github.com/SciTools/cartopy/issues/2086
  - python=3.10 # fixing python version for binder  
